package com.senla.socialnetwork.dao.enumaration;

public enum ArrayIndex {
    FIRST_INDEX_OF_ARRAY(0),
    SECOND_INDEX_OF_ARRAY(1),
    THIRD_INDEX_OF_ARRAY(2),
    FOURTH_INDEX_OF_ARRAY(3),
    FIFTH_INDEX_OF_ARRAY(4),
    SIXTH_INDEX_OF_ARRAY(5),
    SEVENTH_INDEX_OF_ARRAY(6),
    EIGHTH_INDEX_OF_ARRAY(7),
    NINTH_INDEX_OF_ARRAY(8),
    TENTH_INDEX_OF_ARRAY(9),
    ELEVENTH_INDEX_OF_ARRAY(10),
    TWELFTH_INDEX_OF_ARRAY(11),
    THIRTEENTH_INDEX_OF_ARRAY(12),
    FOURTEENTH_INDEX_OF_ARRAY(13),
    FIFTEENTH_INDEX_OF_ARRAY(14),
    SIXTEENTH_INDEX_OF_ARRAY(15),
    SEVENTEENTH_INDEX_OF_ARRAY(16),
    EIGHTEENTH_INDEX_OF_ARRAY(17),
    NINETEENTH_INDEX_OF_ARRAY(18),
    TWENTIETH_INDEX_OF_ARRAY(19),
    TWENTY_FIRST_INDEX_OF_ARRAY(20),
    TWENTY_SECOND_INDEX_OF_ARRAY(21),
    TWENTY_THIRD_INDEX_OF_ARRAY(22),
    TWENTY_FOURTH_INDEX_OF_ARRAY(23),
    TWENTY_FIFTH_INDEX_OF_ARRAY(24),
    TWENTY_SIXTH_INDEX_OF_ARRAY(25),
    TWENTY_SEVENTH_INDEX_OF_ARRAY(26),
    TWENTY_EIGHTH_INDEX_OF_ARRAY(27),
    TWENTY_NINTH_INDEX_OF_ARRAY(28),
    THIRTIETH_INDEX_OF_ARRAY(29),
    THIRTY_FIRST_INDEX_OF_ARRAY(30),
    THIRTY_SECOND_INDEX_OF_ARRAY(31),
    THIRTY_THIRD_INDEX_OF_ARRAY(32);

    public final int index;

    ArrayIndex(int index) {
        this.index = index;
    }
}
