version: '3.3'
services:
  social-network-mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=hrinkov_social_network
      - MYSQL_USER=User
      - MYSQL_PASSWORD=Password
    ports:
      - 3306:3306
    volumes: 
     - ./database/script/dev/init:/docker-entrypoint-initdb.d
  web:
    build:
      context: .
      dockerfile: dockerfile/tomcat/Dockerfile
    restart: on-failure
    depends_on:
      - social-network-mysql
    ports:
      - 2308:8080
