package com.senla.carservice.service.enumaration;

public enum SortParameter {
    SORT_BY_FILING_DATE, SORT_BY_EXECUTION_DATE, BY_PLANNED_START_DATE,
    SORT_BY_PRICE, EXECUTE_ORDER_SORT_BY_FILING_DATE, EXECUTE_ORDER_SORT_BY_EXECUTION_DATE,
    COMPLETED_ORDERS_SORT_BY_FILING_DATE, COMPLETED_ORDERS_SORT_BY_EXECUTION_DATE,
    COMPLETED_ORDERS_SORT_BY_PRICE, CANCELED_ORDERS_SORT_BY_FILING_DATE,
    CANCELED_ORDERS_SORT_BY_EXECUTION_DATE, CANCELED_ORDERS_SORT_BY_PRICE,
    DELETED_ORDERS_SORT_BY_FILING_DATE, DELETED_ORDERS_SORT_BY_EXECUTION_DATE,
    DELETED_ORDERS_SORT_BY_PRICE
}
