package com.senla.carservice.service.enumaration;

public enum OrderSortParameter {
    BY_FILING_DATE,
    BY_EXECUTION_DATE,
    BY_PLANNED_START_DATE,
    BY_PRICE,
    EXECUTE_ORDERS_BY_FILING_DATE,
    EXECUTE_ORDERS_BY_EXECUTION_DATE,
    EXECUTE_ORDERS_BY_PRICE,
    COMPLETED_ORDERS_BY_FILING_DATE,
    COMPLETED_ORDERS_BY_EXECUTION_DATE,
    COMPLETED_ORDERS_BY_PRICE,
    CANCELED_ORDERS_BY_FILING_DATE,
    CANCELED_ORDERS_BY_EXECUTION_DATE,
    CANCELED_ORDERS_BY_PRICE,
    DELETED_ORDERS_BY_FILING_DATE,
    DELETED_ORDERS_BY_EXECUTION_DATE,
    DELETED_ORDERS_BY_PRICE

}
