DROP DATABASE IF EXISTS hrynkou_task10;
CREATE DATABASE IF NOT EXISTS hrynkou_task10;
USE hrynkou_task10;

CREATE TABLE IF NOT EXISTS product(
maker VARCHAR(10),
model VARCHAR(50) PRIMARY KEY,
type VARCHAR(50)
);

CREATE TABLE IF NOT EXISTS pc(
code INT PRIMARY KEY NOT NULL,
model VARCHAR(50) NOT NULL,
FOREIGN KEY (model) REFERENCES product (model),
speed SMALLINT NOT NULL,
ram SMALLINT NOT NULL,
hd REAL NOT NULL,
cd VARCHAR(10) NOT NULL,
price DECIMAL(7,2)
);

CREATE TABLE IF NOT EXISTS laptop(
code INT PRIMARY KEY,
model VARCHAR(50),
FOREIGN KEY (model) REFERENCES product (model),
speed SMALLINT,
ram SMALLINT,
hd REAL,
price DECIMAL(7,2),
screen TINYINT
);

CREATE TABLE IF NOT EXISTS printer(
code INT PRIMARY KEY NOT NULL,
model VARCHAR(50) NOT NULL,
FOREIGN KEY (model) REFERENCES product (model),
color CHAR(1) NOT NULL,
type VARCHAR(10) NOT NULL,
price DECIMAL(7,2)
);
COMMIT;