FROM openjdk
MAINTAINER hrinkovsergey@yandex.ru

RUN mkdir /usr/local/webapps

COPY jar/socialnetwork-spring-boot.jar /usr/local/webapps/

CMD java -jar /usr/local/webapps/socialnetwork-spring-boot.jar